apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: jenkins-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: ["apps", ""] # Add more if Helm needs to manage deployments, services, etc.
  resources: ["deployments", "services"]
  verbs: ["get", "list", "create", "update", "delete"]